import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ScheduleProvider } from '../schedule'
import { AuthProvider } from '@/auth'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'
import SessionProvider from './auth/provider'
import AuthWrapper from '@/components/auth-wrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={`${inter.className} overflow-hidden`}>
        <SessionProvider session={session}>
          <AuthWrapper>
            <AuthProvider>
              <ScheduleProvider>
                {children}
              </ScheduleProvider>
            </AuthProvider>
          </AuthWrapper>
        </SessionProvider>
      </body>
    </html>
  )
}
