import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ScheduleProvider } from '../schedule'
import { AuthProvider } from '@/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-hidden`}>
        <AuthProvider>
          <ScheduleProvider>
            {children}
          </ScheduleProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
